// Shared Clerk appearance for all auth pages — clean, professional, light theme
export const clerkLight = {
  variables: {
    colorBackground: '#ffffff',
    colorInputBackground: '#f9fafb',
    colorInputText: '#111827',
    colorText: '#111827',
    colorTextSecondary: '#6b7280',
    colorPrimary: '#2563eb',
    colorDanger: '#dc2626',
    colorSuccess: '#16a34a',
    borderRadius: '8px',
    fontFamily: "'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif",
    fontSize: '14px',
  },
  elements: {
    rootBox: { width: '100%' },
    card: {
      boxShadow: 'none',
      border: 'none',
      background: 'transparent',
      padding: '0',
      width: '100%',
      maxWidth: '100%',
    },
    headerTitle: { color: '#111827', fontSize: '22px', fontWeight: '600', letterSpacing: '-0.02em' },
    headerSubtitle: { color: '#6b7280', fontSize: '14px' },
    formButtonPrimary: {
      background: '#2563eb',
      color: '#ffffff',
      fontWeight: '500',
      fontSize: '14px',
      borderRadius: '8px',
      boxShadow: 'none',
    },
    formFieldInput: {
      background: '#f9fafb',
      border: '1px solid #e5e7eb',
      color: '#111827',
      borderRadius: '8px',
      fontSize: '14px',
    },
    formFieldLabel: { color: '#374151', fontWeight: '500', fontSize: '13px' },
    dividerLine: { background: '#e5e7eb' },
    dividerText: { color: '#9ca3af', fontSize: '12px' },
    socialButtonsBlockButton: {
      background: '#ffffff',
      border: '1px solid #e5e7eb',
      color: '#374151',
      borderRadius: '8px',
      fontWeight: '500',
    },
    socialButtonsBlockButtonText: { color: '#374151', fontWeight: '500' },
    footerActionLink: { color: '#2563eb', fontWeight: '500' },
    footerActionText: { color: '#6b7280' },
    identityPreviewText: { color: '#111827' },
    otpCodeFieldInput: {
      background: '#f9fafb',
      border: '1px solid #e5e7eb',
      color: '#111827',
      borderRadius: '8px',
    },
    alertText: { color: '#374151' },
  },
}
